title: My Awesome Blog
author: haseebasim
email: haseebzaidi123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A computer scientist who loves to develop web apps. 

# social links
github_username:  [haseebasim](https://github.com/haseebasim) # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
